version: "3.9"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  web:
    image: structej/projetos:reminder-nextjs-1.0
    environment:
      NEXTAUTH_SECRET: ""
      NEXTAUTH_URL: ""
      GOOGLE_CLIENT_ID: ""
      GOOGLE_CLIENT_SECRET: ""
      DATABASE_URL: "mysql://foo:password@db:3306/bar"
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy

      # # http access
      - traefik.http.routers.reminder-nextjs.rule=Host(`reminder.structej.com`)
      - traefik.http.routers.reminder-nextjs.entrypoints=web

      # # https access

      - traefik.http.routers.reminder-nextjs-websecure.rule=Host(`reminder.structej.com`)
      - traefik.http.routers.reminder-nextjs-websecure.entrypoints=websecure
      - traefik.http.routers.reminder-nextjs-websecure.tls=true

      # # Specify to container port
      - traefik.http.routers.reminder-nextjs-websecure.service=reminder-nextjs-service
      - traefik.http.routers.reminder-nextjs.service=reminder-nextjs-service
      - traefik.http.services.reminder-nextjs-service.loadbalancer.server.port=3000

      # # redirect http to https

      - traefik.http.middlewares.reminder-nextjs-redirect-to-websecure.redirectscheme.scheme=https
      - traefik.http.routers.reminder-nextjs.middlewares=reminder-nextjs-redirect-to-websecure

    restart: always
    networks:
      - proxy
      - internal

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: foo
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: bar
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - db:/var/lib/mysql

volumes:
  db: {}
